$(document).ready(function(){
	$("#art1").click(function(){
		$(".panel_art1").slideToggle("slow");
		$(".panel_art2").slideUp("slow");
		$(".panel_art3").slideUp("slow");
		$(".panel_art4").slideUp("slow");
		$(".panel_art5").slideUp("slow");
		$(".panel_art6").slideUp("slow");
		$(".panel_art7").slideUp("slow");
	});
	$("#art2").click(function(){
		$(".panel_art1").slideUp("slow");
		$(".panel_art2").slideToggle("slow");
		$(".panel_art3").slideUp("slow");
		$(".panel_art4").slideUp("slow");
		$(".panel_art5").slideUp("slow");
		$(".panel_art6").slideUp("slow");
		$(".panel_art7").slideUp("slow");
	});
	$("#art3").click(function(){
		$(".panel_art1").slideUp("slow");
		$(".panel_art2").slideUp("slow");
		$(".panel_art3").slideToggle("slow");
		$(".panel_art4").slideUp("slow");
		$(".panel_art5").slideUp("slow");
		$(".panel_art6").slideUp("slow");
		$(".panel_art7").slideUp("slow");
	});
	$("#art4").click(function(){
		$(".panel_art1").slideUp("slow");
		$(".panel_art2").slideUp("slow");
		$(".panel_art3").slideUp("slow");
		$(".panel_art4").slideToggle("slow");
		$(".panel_art5").slideUp("slow");
		$(".panel_art6").slideUp("slow");
		$(".panel_art7").slideUp("slow");
	});
	$("#art5").click(function(){
		$(".panel_art1").slideUp("slow");
		$(".panel_art2").slideUp("slow");
		$(".panel_art3").slideUp("slow");
		$(".panel_art4").slideUp("slow");
		$(".panel_art5").slideToggle("slow");
		$(".panel_art6").slideUp("slow");
		$(".panel_art7").slideUp("slow");
	});
	$("#art6").click(function(){
		$(".panel_art1").slideUp("slow");
		$(".panel_art2").slideUp("slow");
		$(".panel_art3").slideUp("slow");
		$(".panel_art4").slideUp("slow");
		$(".panel_art5").slideUp("slow");
		$(".panel_art6").slideToggle("slow");
		$(".panel_art7").slideUp("slow");
	});
	$("#art7").click(function(){
		$(".panel_art1").slideUp("slow");
		$(".panel_art2").slideUp("slow");
		$(".panel_art3").slideUp("slow");
		$(".panel_art4").slideUp("slow");
		$(".panel_art5").slideUp("slow");
		$(".panel_art6").slideUp("slow");
		$(".panel_art7").slideToggle("slow");
	});
});